name: UnitTests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    name: Unit Test 
    runs-on: ubuntu-latest

    steps:
      - uses: dart-lang/setup-dart@v1
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dart pub get

      - name: Run unit tests
        run: dart test 
      